#port
server:
 port: 6060
 servlet:
    context-path: /UHIP/
  
uhip:
 uhipProps:
   invalidCredentials: Invalid Credentials
   accountDeactivate: Your Account Is De-activated
   accCreationSuccess: Account Created Successfully 
   accCreationFailure: Account Creation Failed
   accCreationEmailSub: UHIP Account Created Successfully
   uhipAdminPhno: 9096717950
   
 #Data Base  
spring:
 jpa:
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    show_sql: true
    format_sql: true
    dialect: org.hibernate.dialect.Oracle10gDialect
 datasource: 
  url: jdbc:oracle:thin:@localhost:1521:xe
  username: uhip_dev
  password: uhip_dev
  driver-class-name: oracle.jdbc.driver.OracleDriver 
  
  # Configure email
 mail:
  host: smtp.gmail.com
  port: 587
  username: devendra13492@gmail.com
  password: Devendra13492@
  properties:
   mail:
    smtp:
      starttls:
       enable: true
       required: true
      auth: true

